package com.company.atms.audit.entity;

public enum AuditAction {
	CREATE,
    UPDATE,
    DELETE,
    STATUS_CHANGE,
    TRANSACTION_DEBIT_SUCCESS,
    TRANSACTION_DEBIT_FAILED,
    TRANSACTION_CREDIT_SUCCESS,
    TRANSACTION_CREDIT_FAILED
}
